In [2]:
a=5
b=[1,3,5,9]
print(b)

[1, 3, 5, 9]


In [3]:
b*2

[1, 3, 5, 9, 1, 3, 5, 9]

In [4]:
type(b)

list

In [5]:
for i in range(4):
    b[i]=b[i]*2
print(b)

[2, 6, 10, 18]


In [1]:
import numpy as np

In [7]:
x = np.array([1,3,5,9])
x*2

array([ 2,  6, 10, 18])

In [8]:
type(x)

numpy.ndarray

In [9]:
y = np.array([ [2,0],[1,0],[2,2],[0,1]])
y

array([[2, 0],
       [1, 0],
       [2, 2],
       [0, 1]])

In [10]:
np.matmul(x,y)

array([15, 19])

In [11]:
x@y

array([15, 19])

In [12]:
x

array([1, 3, 5, 9])

In [12]:
x * y[:,0]

array([ 2,  3, 10,  0])

In [13]:
np.multiply(x,y[:,0])

array([ 2,  3, 10,  0])

# range

In [16]:
range(0,9,2)

range(0, 9, 2)

In [14]:
set(range(0,9,2))

{0, 2, 4, 6, 8}

In [15]:
list(range(0,9,2))

[0, 2, 4, 6, 8]

In [17]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

# VECTORS & MATRICES

In [20]:
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [21]:
np.zeros((3,4),dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [22]:
np.ones((3,4),dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [4]:
x = np.ones((3,4),dtype=np.float32)
x = x / 0
x

C:\Users\mhozc\AppData\Local\Temp/ipykernel_5668/2096666695.py:2: RuntimeWarning: divide by zero encountered in true_divide
  x = x / 0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]], dtype=float32)

In [5]:
x[0,0] = -x[0,0]
x[0,1] = 100
x

array([[-inf, 100.,  inf,  inf],
       [ inf,  inf,  inf,  inf],
       [ inf,  inf,  inf,  inf]], dtype=float32)

In [23]:
np.isinf(x)

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
BigM = 999
np.where(np.isinf(x),BigM,x)

array([[999., 100., 999., 999.],
       [999., 999., 999., 999.],
       [999., 999., 999., 999.]], dtype=float32)

In [8]:
x = np.where(np.isinf(x),BigM,x)

In [9]:
x.max()

999.0

In [10]:
np.maximum(3,1000)

1000

In [11]:
np.maximum(x,1000)

array([[1000., 1000., 1000., 1000.],
       [1000., 1000., 1000., 1000.],
       [1000., 1000., 1000., 1000.]], dtype=float32)

In [12]:
np.minimum(x,500)

array([[500., 100., 500., 500.],
       [500., 500., 500., 500.],
       [500., 500., 500., 500.]], dtype=float32)

In [13]:
np.maximum(x,500)

array([[999., 500., 999., 999.],
       [999., 999., 999., 999.],
       [999., 999., 999., 999.]], dtype=float32)

In [14]:
np.reshape(x,-1)

array([999., 100., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999.], dtype=float32)

In [15]:
np.unique(x)

array([100., 999.], dtype=float32)

In [32]:
np.log(x)

array([[6.906755 , 4.6051702, 6.906755 , 6.906755 ],
       [6.906755 , 6.906755 , 6.906755 , 6.906755 ],
       [6.906755 , 6.906755 , 6.906755 , 6.906755 ]], dtype=float32)

In [16]:
np.log10(x)

array([[2.9995656, 2.       , 2.9995656, 2.9995656],
       [2.9995656, 2.9995656, 2.9995656, 2.9995656],
       [2.9995656, 2.9995656, 2.9995656, 2.9995656]], dtype=float32)

# Fibonnacci Series

In [20]:
n = 12
x = np.zeros(n,np.int32)
x[1]=1

In [21]:
x

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
for i in np.arange(2,n):
    x[i] = x[i-2] + x[i-1]
    print('Fibonnacci[',i,'] = ',x[i])

Fibonnacci[ 2 ] =  1
Fibonnacci[ 3 ] =  2
Fibonnacci[ 4 ] =  3
Fibonnacci[ 5 ] =  5
Fibonnacci[ 6 ] =  8
Fibonnacci[ 7 ] =  13
Fibonnacci[ 8 ] =  21
Fibonnacci[ 9 ] =  34
Fibonnacci[ 10 ] =  55
Fibonnacci[ 11 ] =  89


# Recursion

In [23]:
def fibo(i):
    if (i<=1): 
        result = i
    else:
        result = fibo(i-2) + fibo(i-1)
    return result

In [27]:
fibo(3)

2

In [28]:
fibo(11)

89

# Random Numbers

In [38]:
np.random.uniform(0,1,5)

array([0.98255687, 0.77294104, 0.3892024 , 0.3734568 , 0.87508644])

In [39]:
np.random.uniform(10,15,5)

array([13.58214409, 13.41466506, 11.20947945, 12.211797  , 10.06843167])

In [40]:
np.random.seed(1923)
x = np.random.uniform(-20,120,25)
x

array([ 39.6176768 ,  28.54584975,  71.50396786,  39.93306305,
       -15.55934598,  49.64870361,  67.68260563,  78.51731042,
        82.43171065, 102.91800582,  95.30011515,  15.87675043,
         1.95905965,  11.40036007,  27.25802555,  70.71071556,
        69.5151506 , 107.59093105,  98.38872859,  34.93643777,
        12.66922564,  74.62140314,  81.83816657, -13.90739102,
        72.37101312])

In [41]:
x = x.astype(int)
x

array([ 39,  28,  71,  39, -15,  49,  67,  78,  82, 102,  95,  15,   1,
        11,  27,  70,  69, 107,  98,  34,  12,  74,  81, -13,  72])

In [42]:
np.random.seed(1923)
x = np.random.randint(-20,120,25)
x

array([ 79,  91,  16, -10, 119,  61,  28,  86, 115, 111,  69,  65,  85,
         4,   7,  66,  29, -12,  58,   1,  12,  74, -12, 119,  84])

In [43]:
x = np.clip(x,0,100)
x

array([ 79,  91,  16,   0, 100,  61,  28,  86, 100, 100,  69,  65,  85,
         4,   7,  66,  29,   0,  58,   1,  12,  74,   0, 100,  84])

In [47]:
np.random.seed(1923)
x = np.random.exponential(10,25).astype(int)
x

array([ 5,  4, 10,  5,  0,  6,  9, 12, 13, 21, 17,  2,  1,  2,  4, 10, 10,
       24, 18,  4,  2, 11, 12,  0, 10])

In [49]:
np.random.seed(1923)
np.random.exponential(10,25).astype(int).max()

24

In [51]:
np.random.shuffle(x)
x

array([10,  4, 24, 13,  0,  5, 10, 18,  2,  6,  5,  2, 17,  4, 11,  2, 12,
       10, 10,  1, 12,  0, 21,  4,  9])

# argmin & argmax

In [52]:
print('Max x=',x.max(),' argmax=',np.argmax(x))

Max x= 24  argmax= 2


In [53]:
print('Min x=',x.min(),' argmin=',np.argmin(x, axis=0))

Min x= 0  argmin= 4


In [54]:
x[2]

24

In [55]:
x[np.argmax(x)]

24